### ISSUE TITLE
VOLUME command in Dockerfile incorrect syntax

### ISSUE THREAD

**Issue by salvisbh** [mathieuruellan/docker-piwigo#11]
It seams that the current VOLUME command with multiple volumes is wrong. As i understand it should not contains delimiters in the JSON Array, at least the current one is inconsistent:
VOLUME ["/var/www/galleries", "/var/www/themes", "/var/www/plugins", "/var/www/local", "/var/www/_data/i" "/config"], 

This line is not compatible with the volumes-declarations in a compose-file. Portainer shows the resulting volumes like documentet in the screenshot
![volumes](https://user-images.githubusercontent.com/6686521/33404189-ab424e92-d563-11e7-8cad-0cebb5fde9c4.PNG)

**Comment by mathieuruellan** [comment]
Hello,

Here a copy paste from the docker official doc:

The VOLUME instruction creates a mount point with the specified name and
marks it as holding externally mounted volumes from native host or other
containers. The value can be a JSON array, VOLUME ["/var/log/"], or a plain
string with multiple arguments, such as VOLUME /var/log or VOLUME /var/log
/var/db.

And it works. I suppose that your tool doen't support the JSON syntaxe.

**Comment by mathieuruellan** [comment]
Or perhaps a missing coma before "config" ?

Le 30 nov. 2017 07:44, "Mathieu Ruellan" <mathieu.ruellan@gmail.com> a
écrit :

Hello,

Here a copy paste from the docker official doc:

The VOLUME instruction creates a mount point with the specified name and
marks it as holding externally mounted volumes from native host or other
containers. The value can be a JSON array, VOLUME ["/var/log/"], or a plain
string with multiple arguments, such as VOLUME /var/log or VOLUME /var/log
/var/db.

And it works. I suppose that your tool doen't support the JSON syntaxe.

**Comment by salvisbh** [comment]
Good morning Mathieu (ou plustôt bonjoir 😉 )
Absolutely, the comma solves the problem. In addition, I had to make the permissions executable with chmod entrypoint. sh before building the image locally, otherwise the container would get stuck with an authorization error when starting.
What do you think it would be a big effort for you to dock the versions in dockerhub and not just deploy "latest" versions?
By the way, you have created a cool image, congratulations and many thanks for your fine work.
With best regards from Switzerland

________________________________
Von: Mathieu Ruellan <notifications@github.com>
Gesendet: Thursday, November 30, 2017 7:46:53 AM
An: mathieuruellan/docker-piwigo
Cc: salvisbh; Author
Betreff: Re: [mathieuruellan/docker-piwigo] VOLUME command in Dockerfile incorrect syntax (#11)

Or perhaps a missing coma before "config" ?

Le 30 nov. 2017 07:44, "Mathieu Ruellan" <mathieu.ruellan@gmail.com> a
écrit :

Hello,

Here a copy paste from the docker official doc:

The VOLUME instruction creates a mount point with the specified name and
marks it as holding externally mounted volumes from native host or other
containers. The value can be a JSON array, VOLUME ["/var/log/"], or a plain
string with multiple arguments, such as VOLUME /var/log or VOLUME /var/log
/var/db.

And it works. I suppose that your tool doen't support the JSON syntaxe.

**Comment by salvisbh** [comment]
Thanks to Mathieu, I installed the new version and tested it in cooperation with OAuth - runs perfectly. Thank you very much.

**Comment by mathieuruellan** [comment]
Bonjour, cette année, nous nous sommes accordés une pause.

Bonne journée !

Le dim. 20 mai 2018 à 08:24, Gilles Ganault <gilles.ganault@free.fr> a
écrit :

> Bonjour,
>
> J'aimerais savoir si un meeting est prévu cette année.
>
>
> Merci.
>
> --
> Nantes Cargo Bike
> Prochaine manifestation le 7 juin 2015
> Site Web: http://nantescargobike.fr
> Email: nantescargo@googlegroups.com
> ---
> Vous recevez ce message, car vous êtes abonné au groupe Google
> Groupes Nantes Cargo Bike Meeting.
> Pour vous désabonner de ce groupe et ne plus recevoir d'e-mails le
> concernant, envoyez un e-mail à l'adresse
> nantescargo+unsubscribe@googlegroups.com.
> Pour envoyer un message à ce groupe, adressez un e-mail à
> nantescargo@googlegroups.com.
> Visitez ce groupe à l'adresse https://groups.google.com/group/nantescargo
> .
> Cette discussion peut être lue sur le Web à l'adresse
> https://groups.google.com/d/msgid/nantescargo/c6e125a3-efe2-0a63-6197-8ec0622a9b30%40free.fr
> .
> Pour plus d'options, visitez le site https://groups.google.com/d/optout .
>
