### ISSUE TITLE
Sending mail looks like not working

### ISSUE THREAD

**Issue by malyjaponec** [mathieuruellan/docker-piwigo#15]
I have been trying to find how to configure piwigo in this container to be able to send email. I have exported php config to host machine so I am able to set some things. But it looks like the container does not contain essential programs for it. I do not know if the mailing is useful for everyone but for me the most used feature that needs sending email is resenting passwords :) So I think it is worth to add sendmail or other needed files to the container and be able to do it. What do you think? 

P.S. Maybe I am just stupid and I did not configured it properly.

**Comment by mathieuruellan** [comment]
I'm not expert with php. But I think it needs a phpmailer package. Afterwards, smtp host/port/credentials etc. must be set. And it should be it.
Feel free to send a pull request!

**Comment by malyjaponec** [comment]
OK. I have overlooked that piwigo contains phpmailer. Yes, It does not need sendmail. I will try to investigate this way. Thanks.
