### ISSUE TITLE
new release (tag 13.7) does not work with mount ro

### ISSUE THREAD

**Issue by 4ndreasH** [mathieuruellan/docker-piwigo#24]
I use this great piwigo container with a volume mount like "/galleries:/var/www/galleries:ro" to restrict any write access to my photos. This worked flawlessly with container release tag 12.2.0 with piwigo updated to release 13.7.0.
Since the last container update (tag 13.7 ), piwigo container stops after trying to chown my photos:

```
[...]
piwigo     | chown -R www-data:www-data /var/www
piwigo     | + chown -R www-data:www-data /var/www
piwigo     | chown: changing ownership of '/var/www/galleries/2023/p1.jpg': Read-only file system
[..]
piwigo     | chown: changing ownership of '/var/www/galleries/2023/p2.jpg': Read-only file system
piwigo     | chown: changing ownership of '/var/www/galleries/2023/cover.jpg': Read-only file system
piwigo     | chown: changing ownership of '/var/www/galleries/2023': Read-only file system
piwigo     | chown: changing ownership of '/var/www/galleries': Read-only file system
piwigo exited with code 0
```

With container release 12.2.0 I also had these warnings about Read-only file system but piwigo does not stop. 

I would love to have back the possibility of mounting my photos read only. How can this be done?

4ndreasH

**Comment by mathieuruellan** [comment]
Hello @4ndreasH
Yes i've added a "set -e" in the script! I can add a parameter to disable that; is it good for you?

**Comment by mathieuruellan** [comment]
@4ndreasH you can add override the environment var "BASH_MODE" to empty string. The behaviour should be the same than before!

Kind regards!

**Comment by 4ndreasH** [comment]
Hello Mathieu,
that would bei great, many thanks!
I appreciate your work very much!

regards,
4ndreasH

17.06.2023 14:37:24 Mathieu Ruellan ***@***.***>:

**Comment by 4ndreasH** [comment]
> @4ndreasH you can add override the environment var "BASH_MODE" to empty string. The behaviour should be the same than before!

that works!
