### ISSUE TITLE
php with ldap support (enhancement)

### ISSUE THREAD

**Issue by 4ndreasH** [mathieuruellan/docker-piwigo#28]
I want to use the ldap extension [Ldap Login](https://piwigo.org/ext/extension_view.php?eid=650). This extension depends on php with ldap support. Would it be possible to integrate a php with module php-ldap included?

Kind regards,
4ndreasH

**Comment by GD-Dal** [comment]
I second this.
When trying to enable the ldap_login plugin it gives a warning saying:
Warning: LDAP Extension missing.

Thanks

**Comment by mathieuruellan** [comment]
hello, i've just pushed a commit which adds php-ldap module.

**Comment by 4ndreasH** [comment]
That's great news! I tested this version and it's working flawlessly with ldap login.
Thank you!
