### ISSUE TITLE
php8.1 or 8.2 ?

### ISSUE THREAD

**Issue by bolet** [mathieuruellan/docker-piwigo#29]
The Dockerfile adds php8.1 packages to the image but the entrypoint.sh script (which is built in the Dockerfile) refers to php/8.2
Is it intended?

**Comment by mathieuruellan** [comment]
Hello,
Actually that's a typo and these lines are now useless.
I remove them.

**Comment by mathieuruellan** [comment]
Current version of piwigo doesn't work with php8.2 (default php version in debian bookworm), that's explain why i'm using the repo packages.sury.org
