### ISSUE TITLE
DB name user and password

### ISSUE THREAD

**Issue by bolet** [mathieuruellan/docker-piwigo#30]
In Dockerfile and docker-compose.yml file, I can't see where DB name user and password are specified for the piwigo service, are they hardcoded?
I'm switching from the linuxserver/piwigo image, and expected to be able to specify those values.

**Comment by mathieuruellan** [comment]
Hello,

I think it is set on first launch init page https://piwigo.org/guides/install/manual
Configuration is stored in a data volume. You can edit the "database.inc.php".
