### ISSUE TITLE
Container restarting. Log: `sed: -e expression #1, char 20: expected \ after 'a', 'c' or 'i'`

### ISSUE THREAD

**Issue by dsteinkopf** [mathieuruellan/docker-piwigo#34]
I keep geeting `sed: -e expression #1, char 20: expected \ after `a', `c' or `i'` and my container is restarting.

It seems to be in this line:
https://github.com/mathieuruellan/docker-piwigo/blame/003bd3fcc9dc6130e2271056af90489376fd7d6a/Dockerfile#L73

`sed -i '/^\s*DocumentRoot.*/a \\tSetEnv HTTPS on' /etc/apache2/sites-enabled/000-default.conf`

sed's "s" does not have an option "a". Is this a topo?

**Comment by dsteinkopf** [comment]
BTW. I am only getting this error since the last auto update this night. I am wondering why this did not happen earlier as this change has been done "3 months ago".

**Comment by mathieuruellan** [comment]
Hello,  reproduced. sed  has been updated in bookworm, and they changed the behaviour ... 
I'm fixing that asap.

**Comment by dsteinkopf** [comment]
Oh yes, of course, it is not an s command but an a command.
Your fix makes it work again.

Thank you very much.

**Comment by mathieuruellan** [comment]
Actually, i did'nt find a way to do it still with the "a" command, this workaround is a little bit ugly but it works.

**Comment by dsteinkopf** [comment]
Quoting is a hell... Thank you again.
