### ISSUE TITLE
nginx max_body_size problem?

### ISSUE THREAD

**Issue by gmanic** [mathieuruellan/docker-piwigo#40]
I just had my container updated to the nginx version (latest 14.4.0).
Unfortunately, uploads via piwigo-ng (app) and webform fail now with nginx-error

client intended to send too large body

As far as I found out, this could be solved with max_body_size xxx (nginx-config)
But I don't know, if this could be a problem with piwigo not splitting the files to be uploaded in smaller chunks?

**Comment by gmanic** [comment]
Adding a line with 
`client_max_body_size 100m;`
in /etc/nginx/conf.d/default.conf (inside docker container, in server block) and doing
`nginx -s reload`
fixes the problem. Photos are uploaded with no error.

**Comment by mathieuruellan** [comment]
Thank you @gmanic . I'm in holiday without computer. If you send a pull request, it should be accepted with pleasure.

**Comment by gmanic** [comment]
Sorry for the delay, PR is created.

[PR for client_max_body_size in nginx.conf](https://github.com/mathieuruellan/docker-piwigo/pull/41)

**Comment by gmanic** [comment]
Closed with PR merged
